# Generated by Django 4.0.1 on 2022-01-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_care_physician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_patients', to='hospital.doctor'),
            preserve_default=False,
        ),
    ]
